# This is a basic workflow to help you get started with Actions

name: Publish Docker Image to GitHub 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Publish Docker Images to GPR
      uses: matootie/github-docker@v3.0.0
      with:
        # GitHub Repository Token to log in using.
        # accessToken: 
        # The desired name for the image. Defaults to current repository name.
        imageName: devopsagent
        # The desired tag for the image. Defaults to latest. Optionally accepts multiple tags separated by newline.
        tag: latest
        # Any additional build arguments to use when building the image, separated by newline.
        # Where should GitHub Docker find the Dockerfile, relative to the root of the repository.
        context: .
